# --------------------------------
# Geyser 配置文件
#
# 一个连接Minecraft: 基岩版本 和 Minecraft: Java版本的桥梁.
#
# GitHub: https://github.com/GeyserMC/Geyser
# Discord: https://discord.geysermc.org/
# 汉化: https://smgoro.top/
# --------------------------------

bedrock:
  # 将侦听连接的 IP 地址。
  # 除非您想限制哪些 IP 可以连接到您的服务器，否则没有理由更改此设置。
  address: 0.0.0.0
  # 将侦听的连接端口
  port: 19132
  # 某些服务商会在您每次启动服务器时更改您的 Java 端口，该设置将相同的端口自动用于 基岩版。
  # 此选项会使每次启动服务器时基岩端口与 Java 端口相同。
  # 此选项仅适用于插件版本。
  clone-remote-port: false
  # 将在 我的世界基岩版客户端显示的 MOTD。 如果“passthrough-motd”设置为 true，这玩意就没用了。
  # 如果其中任何一个为空，则相应的字符串将默认为“Geyser”
  motd1: "Geyser"
  motd2: "Another Geyser server."
  # 将发送到 我的世界基岩版客户端的服务器名称。 这在暂停菜单和设置菜单中都可见。
  server-name: "Geyser"
  # 将网络流量压缩到基岩客户端的程度。 数字越大，使用的 CPU 使用率越高，但
  # 使用的带宽越小。 低于 -1 或高于 9 没有任何影响。设置为 -1 以禁用。
  compression-level: 6
  # 是否为客户端启用代理协议。 除非您在 Geyser 实例前运行 UDP 反向代理，否则您不需要此功能。
  enable-proxy-protocol: false
  # 允许使用 PROXY 协议的代理 IP 地址/子网列表。 仅在启用“enable-proxy-protocol”时有效，
  # 并且仅在您无法使用适当的防火墙时才应使用（通常与共享托管服务提供商等一起使用）。
  # 将此列表保留为空意味着没有 IP 地址白名单。
  # 支持 IP 地址和子网。
  #proxy-protocol-whitelisted-ips: [ "127.0.0.1", "172.18.0.0/16" ]
remote:
  # 远程（Java版）服务器的IP地址
  # 如果是“auto”，对于独立版本，远程地址将设置为 127.0.0.1，
  # 对于插件版本，建议将其保留为“auto”，这样 Geyser 将自动配置地址、端口和身份验证类型。
  # 如果安装了Floodgate，则保留为“auto”。
  address: auto
  # 远程（Java版）服务器的端口
  # 对于插件版本，如果地址已设置为“auto”，则端口也将跟随服务器的侦听端口。
  port: 25565
  # 身份认证类型，可使用 offline, online, 或 floodgate (详情见 https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  # 对于插件版本，建议将 `address` 字段保持为“auto”，以便自动配置 Floodgate 支持。 
  # 如果安装了 Floodgate 并且 `address:` 设置为“auto”，则将自动使用“auth-type: floodgate”。
  auth-type: online
  # 允许通过 Geyser 使用基于密码的身份验证方法。 仅在online mode下有用。 
  # 如果这是关闭的，用户必须使用 Geyser 在其桌面上提供的代码向 Microsoft 进行身份验证。
  allow-password-authentication: true
  # 连接服务器时是否启用 PROXY 协议。
  # 这个设置仅在如下情况有用:
  # 1) 您的服务器支持 PROXY 协议（可能不支持）
  # 2) 您可以在代理主配置中启用的选项运行 Velocity 或 BungeeCord。
  # 如果你不知道这玩意是啥，就不要动他！
  use-proxy-protocol: false
  # 将 Bedrock 客户端用于连接到 Java 服务器的主机名转发 
  # 这旨在用于代理上的强制主机
  forward-hostname: false

# Floodgate 使用加密文件来确保来自授权服务器的使用。 
# 这应该指向 Floodgate 生成的公钥（BungeeCord、Spigot 或 Velocity）
# 不使用 Floodgate 时可以忽略这一点。
# 如果您在同一服务器上使用插件版本的 Floodgate，则密钥将自动从 Floodgate 中获取。
floodgate-key-file: key.pem

# 这个XBOX/我的世界基岩版的用户名是 Java 服务器 auth-info 的密钥。
# 这允许自动配置/登录到远程 Java 服务器。
# 如果您有足够的勇气将您的 Mojang 帐户信息放入配置文件中。
# 取消注释下方内容行以启用此功能。 
#userAuths:
#  BedrockAccountUsername: # 你的我的世界基岩版用户名
#    email: javaccountemail@example.com # 你的我的世界Java版正版邮箱
#    password: javaccountpassword123 # 你的我的世界Java版正版密码
#    microsoft-account: true # 帐户是 Mojang 还是 Microsoft 帐户。
#
#  bluerkelp2: 
#    email: not_really_my_email_address_mr_minecrafter53267@gmail.com 
#    password: "this isn't really my password"
#    microsoft-account: false

# 如果存在大量命令，基岩版客户端可能会在第一次打开命令提示符时卡顿。
# 禁用此功能将阻止发送命令补全以解决基岩客户端的卡顿问题。
command-suggestions: true

# 开启 "ping passthrough" 配置将会从Java版服务器同步这三个数据 - MOTD显示, 在线玩家人数 和/或 从Java服务器检索到的协议名称。
# 将 MOTD 从远程服务器中继到基岩玩家。
passthrough-motd: false
# 中继协议名称（例如 BungeeCord [X.X]，Paper 1.X） - 只有在使用自定义协议名称时才真正有用！ 
# 这也将显示在 MCSrvStatus 等网站上。 <mcsrvstat.us>
passthrough-protocol-name: false
# 将远程服务器的玩家数量和最大玩家数量传递给基岩玩家。
passthrough-player-counts: false
# 启用 LEGACY ping 直通。 除非您的 MOTD 或玩家数量未正确显示，否则无需启用此功能。
# 此选项在独立时不执行任何操作。
legacy-ping-passthrough: false
# ping 远程服务器的频率，以秒为单位。 仅与独立或旧式 ping 直通相关。
# 如果您遇到 BrokenPipe 错误，请增加。 
ping-passthrough-interval: 3

# 是否将玩家 ping 转发到服务器。 虽然启用此功能将使基岩玩家获得更准确的 ping，但也可能导致玩家更容易超时。
forward-player-ping: false

# 可以连接的最大玩家数量。 目前这只是表面数据，实际上并不限制玩家数量。
max-players: 100

# 开启后调试消息应该会发送在控制台
debug-mode: false

# 允许第三方披风可见。 目前允许：
# OptiFine 披风、LabyMod 披风、5Zig 披风和 MinecraftCapes
allow-third-party-capes: true

# 允许第三方 deadmau5 ears可见。 目前允许：
# MinecraftCapes
allow-third-party-ears: false

# 允许发送虚拟攻击缓冲显示。 基岩玩家没有看到冷却时间，因为基岩版没有缓冲，像Java 1.8 版本往前那样。
# 可以使用 title, actionbar 或 false
show-cooldown: title

# 控制是否向玩家显示坐标。
show-coordinates: true

# 基岩玩家是否被阻止执行他们的脚手架式桥接。
disable-bedrock-scaffolding: false

# 基岩玩家是否可以在物品栏外右键单击以替换物品栏中的盔甲，即使盔甲槽已被占用（Java 版不允许）
always-quick-change-armor: false

# 如果设置，当基岩玩家执行任何表情时，它将交换副手和主手物品，就像 Java 版键绑定一样
# 可以设置三个选项：
# disabled - 默认/后备，不应用此解决方法
# no-emotes - 表情不会发送给其他基岩客户端，并且副手将被交换。 这有效地禁用了所有表情。
# emotes-and-offhand - 表情将被发送给基岩客户端，副手将被交换
emote-offhand-workaround: "disabled"

# 如果我们没有客户要求的语言环境，则使用默认语言环境。 取消注释以不使用默认系统语言。
# default-locale: en_us

# 指定将图像缓存到磁盘的天数，以节省从 互联网 下载它们的时间。
# 设置成0则为关闭此项 (默认: 0)
cache-images: 0

# 允许显示自定义头骨。 保持启用它们可能会导致旧/较弱设备的性能下降。
allow-custom-skulls: true

# 是否添加（目前仅）熔炉矿车作为游戏中的单独项目，这在基岩版中通常不存在。
# 只有在使用不使用“传输数据包”类型的服务器切换的代理时才需要禁用此功能。
# 如果禁用此功能，熔炉矿车物品将映射到漏斗矿车物品。
# 此选项需要重新启动 Geyser 才能应用更改其设置。
add-non-bedrock-items: true

# 基岩阻止在下界 Y127 上方建造和展示方块。
# 此配置选项通过将 Nether 维度 ID 更改为 End ID 来解决此问题。
# 这样做的主要缺点是整个下界将有相同的红色雾，而不是每个生物群落都有不同的雾。
above-bedrock-nether-building: false

# 强制客户端加载所有资源包（如果有）。
# 如果设置为 false，它允许用户连接到服务器，即使他们不想下载资源包。
force-resource-packs: true

# 允许解锁 Xbox 成就。
# 这会禁用所有在游戏中成功运行 基岩版 的命令，否则 基岩版 会认为您在作弊。
xbox-achievements-enabled: false

# bStats 是一个完全匿名的统计跟踪器，仅跟踪有关 Geyser 的基本信息，例如在线人数、使用 Geyser 的服务器数量，
# 正在使用什么操作系统等。您可以在此处了解有关 bStats 的更多信息： https://bstats.org/.
# https://bstats.org/plugin/server-implementation/GeyserMC
metrics:
  # 是否启用指标
  enabled: true
  # 服务器的UUID，不要更改他!
  uuid: 9f06996a-2206-4aba-891a-fb3419549d75

# 高级选项 - 除非您知道自己在做什么，否则请勿触摸！

# Geyser 在每个 Scoreboard 数据包之后更新 Scoreboard，但是当 Geyser 试图
# 每秒处理大量的 scoreboard 数据包时会导致严重的延迟。
# 此选项允许您指定在每秒多少记分牌数据包之后，记分牌更新将被限制为每秒四次更新。
scoreboard-packet-threshold: 20

# 允许来自 ProxyPass 和 Waterdog 的连接。
# 查看 https://www.spigotmc.org/wiki/firewall-guide/ 寻求帮助 - 使用 UDP 而不是 TCP。
enable-proxy-connections: false

# Internet 支持的最大 MTU 为 1492，但可能会导致数据包碎片问题。
# 1400 是默认值。
mtu: 1400

# 是否直接连接到 Java 服务器而不创建 TCP 连接。
# 仅当与数据包或网络接口的插件无法与 Geyser 一起正常工作时，才应禁用此功能。
# 如果在插件版本上启用，远程地址和端口部分将被忽略
# 如果在插件版本上禁用，预计将性能下降和延迟增加
use-direct-connection: true

config-version: 4
